import DrawerAppBar from "@components/navbar";
import "./globals.css";
import 'react-phone-input-2/lib/style.css';
import 'font-awesome/css/font-awesome.min.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Inter } from "next/font/google";
import NextAuthProvider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <main>
            <DrawerAppBar />
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
